// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:431929695285:web:e3e163f56bdfa59f84e57c',
    messagingSenderId: '431929695285',
    projectId: 'cybersagedb',
    authDomain: 'cybersagedb.firebaseapp.com',
    storageBucket: 'cybersagedb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:431929695285:android:72f5f61f79ae04a184e57c',
    messagingSenderId: '431929695285',
    projectId: 'cybersagedb',
    storageBucket: 'cybersagedb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:431929695285:ios:732f86ba45f1c5b684e57c',
    messagingSenderId: '431929695285',
    projectId: 'cybersagedb',
    storageBucket: 'cybersagedb.firebasestorage.app',
    iosBundleId: 'com.example.cybersage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:431929695285:ios:732f86ba45f1c5b684e57c',
    messagingSenderId: '431929695285',
    projectId: 'cybersagedb',
    storageBucket: 'cybersagedb.firebasestorage.app',
    iosBundleId: 'com.example.cybersage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:431929695285:web:f5ebd7a4dbfa51d284e57c',
    messagingSenderId: '431929695285',
    projectId: 'cybersagedb',
    authDomain: 'cybersagedb.firebaseapp.com',
    storageBucket: 'cybersagedb.firebasestorage.app',
  );
}
